# https://github.com/marketplace/actions/profile-readme-development-stats
# https://github.com/athul/waka-readme

name: Waka Readme

on:
  workflow_dispatch: # for manual workflow trigger
  schedule:
    - cron: '0 0 * * *' # runs at every 12AM UTC

jobs:
  update-readme:
    name: WakaReadme DevMetrics
    runs-on: ubuntu-latest
    steps:
#       - uses: athul/waka-readme@master
#         with:
#           WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
#           # GH_TOKEN: ${{ secrets.GH_TOKEN }}
#           TIME_RANGE: last_7_days

      - uses: anmol098/waka-readme-stats@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          SHOW_LINES_OF_CODE: True
          SHOW_DAYS_OF_WEEK: False
          SHOW_COMMIT: False
          SHOW_LANGUAGE_PER_REPO: False #doesn't show repos in organizations -> hide for now
          SHOW_SHORT_INFO: False #doesn't show repos in organizations neither
